### ISSUE TITLE
Support for topic initialization

### ISSUE THREAD

**Issue by joshfg** [adilsoncarvalho/gcloud-pubsub-emulator-docker#1]
I want to initialize the PubSub instance with a few topics when the container starts (so that I can docker-compose the emulator with another service which expects these PubSub topics to already exist). Since the PubSub emulator seems to store topics in memory, I think the initialization will need to happen every time a new container launches. Is there any support for doing this at the moment?

**Comment by adilsoncarvalho** [comment]
Hy @joshfg 

The emulator provides [support for persistent storage][0] and it is actually storing all its data onto a volume as you can see on [this line of the Dockerfile][1].

All you need to do it to mount this volume on your docker/docker-compose in order to be able to reuse your previously creates channels.

I hope this helps you.

Have a great one!

[0]: https://cloud.google.com/sdk/gcloud/reference/beta/emulators/pubsub/
[1]: https://github.com/adilsoncarvalho/gcloud-pubsub-emulator-docker/blob/master/Dockerfile#L9
